### VSCodeで、拡張機能 REST Clientをインストール
@host = http://localhost:8080/detect_and_findsimilars

### Success

POST {{host}}
content-type: application/octet-stream

< images/fujihira.jpg

### Failure

POST {{host}}
content-type: application/octet-stream

< test.rs

### Two faces

POST {{host}}
content-type: application/octet-stream

< images/prowrestling.jpg

### No face

POST {{host}}
content-type: application/octet-stream

< images/logo.png
